[1]
catalognumber = "OPCD-1016"
date = "2014-04-27"
album = "メインヒロイン(仮)"
tracks = [
    [1, "メインヒロイン(仮)", "おでんぱ☆スタジオ", ""],
    [2, "ろり☆ぱんっ～めんぱんつりみっくちゅ～", "おでんぱ☆スタジオ", ""],
    [3, "めいんひろいんさくぶん", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/1616647a-8a11-40fc-83e9-22dedb90aa4d"]

[2]
catalognumber = "OPCD-1021"
date = "2015-08-16"
album = "うぉーたーぱーくパラダイス"
tracks = [
    [1, "水着はセパレイト▼", "おでんぱ☆スタジオ", "1"],
    [2, "渋々プールに行ったらウォータースライダーから 幼女が流しそうめんみたいに滑ってきた件", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/ec25cdf2-a7f2-4061-92aa-792d635fa60d"]

[3]
catalognumber = "OPCD-1023"
date = "2015-12-31"
album = "壁ドン☆"
tracks = [
    [1, "壁ドン☆", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/040ecf7a-1403-4e98-8194-60f0a359e788"]

[4]
catalognumber = "OPCD-1002"
date = "2010-10-14"
album = "おでんぱ☆夏祭り"
tracks = [
    [1, "おでんぱ☆音頭～紳士と幼女の夏祭り～", "おでんぱ☆スタジオ", "0"],
    [2, "夏だ！海だ！スク水だ！", "おでんぱ☆スタジオ", "0"],
    [3, "幼女戦隊ゴエンジャー", "おでんぱ☆スタジオ", "0"],
    [4, "でぱらじ☆ふぁーすと", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/97d402af-1cde-40b9-ad1e-25f4144132c2"]

[5]
catalognumber = "OPCD-1004"
date = "2011-05-01"
album = "ボクとまほうとあいすくりーむ☆"
tracks = [
    [1, "あまなCHU☆あばんちゅ～る～ペロペロしちゃらめぇ～", "おでんぱ☆スタジオ", ""],
    [2, "ショタとよばないで！～今日からｘｘｘは自分で洗うよ～", "おでんぱ☆スタジオ", ""],
    [3, "はにほれはっぴぃ♪", "おでんぱ☆スタジオ", ""],
    [4, "でぱらじ☆さぁど", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/37570d8a-adfd-43ff-ad91-11d215acb4f1"]

[6]
catalognumber = "OPCD-1014"
date = "2013-10-27"
album = "びっ栗☆秋味ふぇあ"
tracks = [
    [1, "クリむき！", "おでんぱ☆スタジオ", "1"],
    [2, "まつたけみっけ♪", "おでんぱ☆スタジオ", "1"],
    [3, "でぱらじ☆とぅえるぶす", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/50d08f04-2902-4096-8045-c5930fef0ae0"]

[7]
catalognumber = "OPCD-1008"
date = "2012-04-30"
album = "おでんぱ☆学園 初等科"
tracks = [
    [1, "おでんぱ☆身体測定", "おでんぱ☆スタジオ", ""],
    [2, "DokiDoki調理実習", "おでんぱ☆スタジオ", ""],
    [3, "つるつるぺったん娘体操～世界つるぺた協会公式体操～", "おでんぱ☆スタジオ", ""],
    [4, "ぺろぺろちゅっちゅぺろりっちゅ！", "おでんぱ☆スタジオ", ""],
    [5, "つるぺたは世界を救う～ピコピコmix略してつるピコ～", "おでんぱ☆スタジオ", ""],
    [6, "でぱらじ☆せぶんす", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/59f5ae9a-faef-489e-8059-8dc48bbd281c"]

[8]
catalognumber = "OPCD-1007"
date = "2011-12-31"
album = "ろりーたプラネット★ミ"
tracks = [
    [1, "ロリコン・セーバー～地球のロリコンたちを護れ～", "おでんぱ☆スタジオ", ""],
    [2, "幼なじみの恋～のすたるじあmix～", "おでんぱ☆スタジオ", "0"],
    [3, "なめこのうた", "おでんぱ☆スタジオ", ""],
    [4, "でぱらじ☆しっくすす", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/1d4b5f63-0c6f-4cb5-a9a6-26218919c57c"]

[9]
catalognumber = "OPCD-1012"
date = "2013-04-29"
album = "おでんぱ☆スタジオ～もう4ちゃい～"
tracks = [
    [1, "しゅごいしっぽでしゅぽぽぽ", "おでんぱ☆スタジオ", ""],
    [2, "きゅんきゅんツインテール", "おでんぱ☆スタジオ", ""],
    [3, "あほ毛なMyLife", "おでんぱ☆スタジオ", ""],
    [4, "SingleAge", "おでんぱ☆スタジオ", ""],
    [5, "DokiDoki二人三脚～もっと!どきどき!!バージョン～", "おでんぱ☆スタジオ", ""],
    [6, "でぱらじ☆いれぶんす", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/bf346774-2671-44cb-8d52-a10b81c61489"]

[10]
catalognumber = "OPCD-1015"
date = "2013-12-31"
album = "白い○人"
tracks = [
    [1, "白い○人", "おでんぱ☆スタジオ", "0"],
    [2, "貧乳シンデレラ～おっぱいがそんなにエライのか！？～", "おでんぱ☆スタジオ", "0"],
    [3, "世界の迷作絵本「貧乳シンデレラ」", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/eee71f17-96ef-4051-90a8-50a80ebccbbd"]

[11]
catalognumber = "OPCD-1013"
date = "2013-08-12"
album = "おでんぱ☆夏祭り～でらっくちゅ～"
tracks = [
    [1, "らぷそでぃ☆淫☆ばするーむ", "おでんぱ☆スタジオ", "1"],
    [2, "肝試し現場でうらめしや", "おでんぱ☆スタジオ", "0"],
    [3, "おでんぱ☆音頭～紳士と幼女の夏祭り～", "おでんぱ☆スタジオ", "0"],
    [4, "夏だ！海だ！スク水だ！", "おでんぱ☆スタジオ", "0"],
    [5, "幼女戦隊ゴエンジャー", "おでんぱ☆スタジオ", "0"],
    [6, "でぱらじ☆ふぁーすと", "おでんぱ☆スタジオ", "0"],
    [7, "ようじょが３分間はかるボイストラック", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/47956ed3-7052-404b-a36f-973db7631974"]

[12]
catalognumber = "OPCD-1010"
date = "2012-10-28"
album = "Lolly'sへようこそ!"
tracks = [
    [1, "Lolly’sへようこそ！", "おでんぱ☆スタジオ", "1"],
    [2, "しゃらら", "おでんぱ☆スタジオ", "1"],
    [3, "でぱらじ☆ないんす", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/974887b8-cca6-40f4-ad34-04375e6f5582"]

[13]
catalognumber = "OPCD-1009"
date = "2012-08-11"
album = "らぶでんぱ"
tracks = [
    [1, "ぴ・ぴ・ぴ", "おでんぱ☆スタジオ", ""],
    [2, "しーさいど☆でーと", "おでんぱ☆スタジオ", ""],
    [3, "らぶそんぐみたいなうた", "おでんぱ☆スタジオ", ""],
    [4, "だいしゅきほ～るど", "おでんぱ☆スタジオ", ""],
    [5, "朝まで生ｘｘｘ「LOVEってなんだ!?」 スペシャル!!", "おでんぱ☆スタジオ", ""],
    [6, "でぱらじ☆えいとす", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/367f8526-b92a-410f-9b9f-fc7e2b612d12"]

[14]
catalognumber = "OPCD-1022"
date = "2015-10-25"
album = "リアル充実ごっこ～trick or rea10～"
tracks = [
    [1, "リアル充実ごっこ～trick or rea10～▼", "おでんぱ☆スタジオ", "0"],
    [2, "曲ができません", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/69b1d1cd-0a77-41b3-b240-4cce4ed8df1a"]

[15]
catalognumber = "OPCD-1001"
date = "2010-05-05"
album = "おでんぱ☆スタジオ"
tracks = [
    [1, "えぶり～らぶり～はっぴ～たいむ", "おでんぱ☆スタジオ", "0"],
    [2, "つるぺたは世界を救う！？ ～世界つるぺた協会公式ソング～", "おでんぱ☆スタジオ", "0"],
    [3, "ツンデレとかじゃないんだからねっ！", "おでんぱ☆スタジオ", "1"],
    [4, "おでんぱようちえんのうた♪", "おでんぱ☆スタジオ", "0"],
    [5, "しょうがないから、いてあげるっ！", "おでんぱ☆スタジオ", "0"],
    [6, "おねがい☆ギャルゲマスター！", "おでんぱ☆スタジオ", "0"],
    [7, "幼なじみの恋", "おでんぱ☆スタジオ", "0"],
    [8, "戦え☆チビナナン", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/fd55a144-8677-4128-b084-617d54c6daf3"]

[16]
catalognumber = "OPCD-1019"
date = "2014-12-30"
album = "キャッチン☆こたつ"
tracks = [
    [1, "キャッチン☆こたつ♥", "おでんぱ☆スタジオ", "0"],
    [2, "きみにツンツン", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/26f60547-bd79-4fae-ae45-16c29612f52b"]

[17]
catalognumber = "OPCD-1018"
date = "2014-10-26"
album = "Ochingin"
tracks = [
    [1, "おちんぎんくだひゃい♥", "おでんぱ☆スタジオ", ""],
    [2, "くんくんくん", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/79cd6557-1515-48ee-99e1-fd85cccf635f"]

[18]
catalognumber = "ODENPA-001"
date = "2009-12-29"
album = "C77落選記念CD"
tracks = [
    [1, "えぶり～らぶり～はっぴ～たいむ", "おでんぱ☆スタジオ", "0"],
    [2, "けもみみDANCE", "おでんぱ☆スタジオ", "0"],
    [3, "でぱらじ第00回～C77落選記念特別版!", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/3747662e-06be-4601-b10b-e1073d3bb8dd"]

[19]
catalognumber = "OPCD-1005"
date = "2011-08-13"
album = "ろり☆パンでみっく"
tracks = [
    [1, "クンカ＝パラダイス ～幼女化合物についての仮説と実験～", "おでんぱ☆スタジオ", ""],
    [2, "にゃあにゃあにゃあ", "おでんぱ☆スタジオ", ""],
    [3, "ろり☆ぱんっ", "おでんぱ☆スタジオ", ""],
    [4, "でぱらじ☆ふぉーす", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/2979d57e-6b75-41b8-b9d8-91277fd95634"]

[20]
catalognumber = "OPCD-1006"
date = "2011-10-30"
album = "ぴこみこ☆"
tracks = [
    [1, "ぴこみこ＠オンライン～おでんぱ神社へようこそ～", "おでんぱ☆スタジオ", "0"],
    [2, "うれしょんﾟ･*:.｡.", "おでんぱ☆スタジオ", "1"],
    [3, "ぽにっとふぁいやー☆", "おでんぱ☆スタジオ", "0"],
    [4, "Girl Friend", "おでんぱ☆スタジオ", "1"],
    [5, "けもみみDANCE！～もーっちゅ！りみっくCHU☆～", "おでんぱ☆スタジオ", "0"],
    [6, "でぱらじ☆ふぃふす", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/cbd7c773-a256-4fbf-88f6-6573c67c4823"]

[21]
catalognumber = "OPCD-1011"
date = "2012-12-31"
album = "おでんぱ☆幼女合唱"
tracks = [
    [1, "ぐろりあ♪", "おでんぱ☆スタジオ", ""],
    [2, "ロリロリ詐欺にご用心！", "おでんぱ☆スタジオ", ""],
    [3, "でぱらじ☆てんす", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/4998b7cd-cd84-4a5f-89e2-5e74a7b1d320"]

[22]
catalognumber = "OPCD-1024"
date = "2016-04-24"
album = "ロリの極み幼女。～ありがとう、バイ・スプリング…ダメ絶対！～"
tracks = [
    [1, "ロリの極み幼女。～ありがとう、バイ・スプリング…ダメ絶対！～", "おでんぱ☆スタジオ", "1"],
    [2, "しあわせＴＩＭＥＲ", "おでんぱ☆スタジオ", "1"],
]
links = ["https://beta.musicbrainz.org/release/1cde9365-58ba-4272-96ac-7a752de4b111"]

[23]
catalognumber = "OPCD-1017"
date = "2014-08-17"
album = "チキンナゲット(黴)"
tracks = [
    [1, "チキンナゲット（黴）", "おでんぱ☆スタジオ", "1"],
]
links = ["https://beta.musicbrainz.org/release/718a6ae8-5bb1-47b6-8f3c-e689e89425d2"]

[24]
catalognumber = "OPCD-1003"
date = "2010-10-31"
album = "おでんぱ☆運動会"
tracks = [
    [1, "おでんぱ☆行進曲", "おでんぱ☆スタジオ", ""],
    [2, "DokiDoki二人三脚", "おでんぱ☆スタジオ", ""],
    [3, "ないしょのダンス～おにぃちゃんのえっちっち♪～", "おでんぱ☆スタジオ", ""],
    [4, "でぱらじ☆せかんど", "おでんぱ☆スタジオ", ""],
]
links = ["https://beta.musicbrainz.org/release/b43ab4c2-1ed7-4378-b313-363a64f12b19"]

[25]
catalognumber = "OPCD-1020"
date = "2015-04-26"
album = "ロリッ子羊ちゃんクライシス?!"
tracks = [
    [1, "ロリッ子羊ちゃんクライシス!?おにーちゃんそこはらめぇ～らめぇ～めぇ～2015(未年)Ver.", "おでんぱ☆スタジオ", "1"],
    [2, "ツイッターってちょろいわぁ♪", "おでんぱ☆スタジオ", "0"],
]
links = ["https://beta.musicbrainz.org/release/a88d7c4a-b465-42bd-9c92-2eb14e5fe833"]

[26]
catalognumber = ""
date = "2017-04-30"
album = "お☆んぱスタジオ"
tracks = [
    [0, "電磁波を☆す歌", "かなで(CV：ねこめ),ドミソ(CV：ほたる)", "0"],
    [0, "YESひじきクリニック（フェイシャルエステ編）", "ゆな(CV：なつき)", "0"],
    [0, "お☆んぱスタジオに気をつけろ!!", "ドミソ(CV：ほたる)", "1"],
]
links = ["https://www.dojin-music.info/cd/5956"]

[27]
catalognumber = ""
date = "2014-12-30"
album = "ときめきほたるたん"
tracks = [
    [0, "ときめきのメロディ♪", "ほたるたん", "1"],
    [0, "ロザリオとロマンス", "ほたるたん", "0"],
    [0, "不夜城プリンセス", "ほたるたん", "0"],
    [0, "SweetPink Rabbit", "ほたるたん", "0"],
    [0, "lovely snow", "ほたるたん", "1"],
    [0, "トライアングル☆メリーゴーランド", "ほたるたん", "0"],
]
links = ["https://www.dojin-music.info/cd/5837"]

[28]
catalognumber = ""
date = "2016-08-14"
album = "ときめきほたるたん２"
tracks = [
    [1, "ときめき…夏未満。", "ほたるたん", "1"],
    [2, "オトナ♡Happy", "ほたるたん", "0"],
    [3, "ヒミツの経験", "ほたるたん", "0"],
    [4, "ラブ・サーフィン", "ほたるたん", "0"],
    [5, "Juicy!とろとろトロピカル", "ほたるたん", "0"],
    [6, "SSDR_PARTY", "ほたるたん", "0"],
    [7, "泡沫想い", "ほたるたん", "0"],
    [8, "夏色ノクターン", "ほたるたん", "1"],
    [9, "ごめんね人魚姫", "ほたるたん", "0"],
    [10, "Charmy Smile PRINCESS", "ほたるたん", "0"],
    [11, "おひるね日和", "ほたるたん", "0"],
    [12, "U", "ほたるたん", "0"],
    [13, "虹色カレイドスコープ", "ほたるたん", "0"],
]
links = ["https://www.dojin-music.info/cd/5838"]

[29]
catalognumber = ""
date = "2017-10-29"
album = "恋のICBM"
tracks = [
    [0, "恋のICBM", "おでんぱ☆スタジオ", "0"],
]
links = ["https://www.dojin-music.info/cd/5954"]

[30]
catalognumber = ""
date = "2016-10-30"
album = "新譜かってください"
tracks = [
    [1, "【拡散希望】【もう時間がありません】助けてください！新譜買ってください！！１００部発注のはずが間違えて１０００部発注してしまいました！このままでは次のCDの制作費がだせません（＞＜）ご支援よろしくお願いします！【知らないでは済まない】【興味がなくてもRTを】", "おでんぱ☆スタジオ", "0"],
    [2, "おうまさんごっこステークス（ＧⅠ）～あたしのおにーちゃんがいちばんはやいもんっ～", "おでんぱ☆スタジオ", "1"],
]
links = ["https://www.dojin-music.info/cd/5955"]
