[1]
catalognumber = "VGR-2"
date = "2005-08-24"
album = "アイスキャンディー / MAKO"
tracks = [
    [1, "アイスキャンディー", "MAKO", 2],
    [2, "あいコトバ", "MAKO", 2],
    [3, "アイスキャンディー＊karaoke", "MAKO", 1],
    [4, "あいコトバ＊karaoke", "MAKO", 1],
]
links = ["https://beta.musicbrainz.org/release/242a4cdc-8bc2-49e4-808c-d69c0be9d2b3", "https://vgmdb.net/album/61120"]

[2]
catalognumber = "VGR-1"
date = "2005-08-24"
album = "晴れのちハレ! / 富田麻帆"
tracks = [
    [1, "晴れのちハレ！", "富田麻帆", 2],
    [2, "オレンジ色のひまわり", "富田麻帆", 2],
    [3, "晴れのちハレ！＊karaoke", "富田麻帆", 1],
    [4, "オレンジ色のひまわり＊karaoke", "富田麻帆", 1],
]
links = ["https://beta.musicbrainz.org/release/981e4958-4eec-4a2e-a7c3-55794bed8b6e", "https://vgmdb.net/album/61121"]

[3]
catalognumber = "SVWC-7291"
date = "2005-10-26"
album = "かみちゅ!◎オリジナル・サウンドトラック"
tracks = [
    [1, "恋の自習時間", "池頼広", 1],
    [2, "君につづく坂道", "池頼広", 1],
    [3, "ちゅう学生がゆく！", "池頼広", 1],
    [4, "バチあたるぞ！", "池頼広", 1],
    [5, "恋は、ふしぎ", "池頼広", 1],
    [6, "自転車で帰ろう", "池頼広", 1],
    [7, "時はゆっくり流れてる", "池頼広", 1],
    [8, "なんでもありません", "池頼広", 1],
    [9, "もののけだよ全員集合！", "池頼広", 1],
    [10, "すこし、ふしぎ", "池頼広", 1],
    [11, "アイラブユーは川を越えて", "池頼広", 1],
    [12, "神々Cガール", "池頼広", 1],
    [13, "センチメンタル・カントリー・ロマンス", "池頼広", 1],
    [14, "いつだってお昼寝ちゅう", "池頼広", 1],
    [15, "あたふた あたふた", "池頼広", 1],
    [16, "天国時間", "池頼広", 1],
    [17, "恋の片道フェリー", "池頼広", 1],
    [18, "夢色坂道", "池頼広", 1],
    [19, "あの夏の坂道", "池頼広", 2],
    [20, "ウキウキ寄り道オーマイガッ！", "池頼広", 1],
    [21, "ちゅう学生がもっとゆく！", "池頼広", 1],
    [22, "海はグー！瀬戸内サーフィン天国", "池頼広", 1],
    [23, "晴れのちハレ！（TV version）", "富田麻帆", 1],
    [24, "アイスキャンディー（TV version）", "MAKO", 1],
]
links = ["https://beta.musicbrainz.org/release/e1c8e1af-7ca2-45c0-9e60-51669c4dac13", "https://vgmdb.net/album/17770"]

[4]
catalognumber = "5352-2"
date = "2006-10-10"
album = "KamiChu! Original Soundtrack"
tracks = [
    [1, "Study Period in Love", "池頼広", 1],
    [2, "The Hill That Leads to You", "池頼広", 1],
    [3, "Junior High School Students March On!", "池頼広", 1],
    [4, "It's Bad Karma!", "池頼広", 1],
    [5, "Love Is Mysterious", "池頼広", 1],
    [6, "Let's Go Home by Bike", "池頼広", 1],
    [7, "Time Flows Slowly", "池頼広", 1],
    [8, "It's Nothing", "池頼広", 1],
    [9, "Come Together, Ghosts and Goblins!", "池頼広", 1],
    [10, "A Little Mysterious", "池頼広", 1],
    [11, "Saying 'I Love You' Across the River", "池頼広", 1],
    [12, "Divine Girls", "池頼広", 1],
    [13, "Sentimental Country Romance", "池頼広", 1],
    [14, "Nap Time Anytime", "池頼広", 1],
    [15, "Rush, Rush, Rush", "池頼広", 1],
    [16, "Paradise Time", "池頼広", 1],
    [17, "The One-Way Ferry of Love", "池頼広", 1],
    [18, "Dream Colored Hill", "池頼広", 1],
    [19, "The Hill From That Summer", "池頼広", 1],
    [20, "An Exciting Detour Oh My God!", "池頼広", 1],
    [21, "Junior High School Students March Further On!", "池頼広", 1],
    [22, "The Beach Is Good! Setouchi Surfin' Paradise", "池頼広", 1],
    [23, "Clear, Later Clear! (TV version)", "富田麻帆", 1],
    [24, "Ice Candy (TV version)", "MAKO", 1],
]
links = ["https://beta.musicbrainz.org/release/f5a851fb-7b4d-4cca-918c-04a6ff94edaf", "https://vgmdb.net/album/25854"]
