[1]
catalognumber = "LACM-14667"
date = "2017-10-25"
album = "ココロニツボミ / eufonius"
tracks = [
    [1, "ココロニツボミ", "eufonius", 2],
    [2, "はじめて", "eufonius", 1],
    [3, "ココロニツボミ (Instrumental)", "eufonius", 1],
    [4, "はじめて (Instrumental)", "eufonius", 1],
]
links = ["https://beta.musicbrainz.org/release/3e3dba60-2f97-4bdf-ae4f-7377a1fcef11", "https://vgmdb.net/album/70620"]

[2]
catalognumber = "LACM-14697"
date = "2017-12-13"
album = "此花亭の四季 / 此花亭仲居の会"
tracks = [
    [1, "春ウララ、君ト咲キ誇ル", "此花亭仲居の会[柚(CV.大野柚布子)、皐(CV.秦佐和子)、棗(CV.諏訪彩花)、蓮(CV.久保田梨沙)、櫻(CV.加隈亜衣)、桐(CV.沼倉愛美)]", 2],
    [2, "夏咲き恋花火", "棗(CV.諏訪彩花)、蓮(CV.久保田梨沙)", 2],
    [3, "茜空、君舞フ紅葉ノ散歩道", "櫻(CV.加隈亜衣)、桐(CV.沼倉愛美)", 2],
    [4, "雪華煌めく家路にて", "柚(CV.大野柚布子)、皐(CV.秦佐和子)", 2],
]
links = ["https://beta.musicbrainz.org/release/eced6e07-ba97-431c-a2f8-7b07d49f1c67", "https://vgmdb.net/album/71406"]

[3]
catalognumber = "LACA-9565"
date = "2018-01-10"
album = "TVアニメ『このはな綺譚』おりじなるさうんどとらっく Disc 1 [LACA-9565]"
tracks = [
    [1, "「このはな綺譚」〜メインテーマ〜", "菊地創", 1],
    [2, "此花亭", "菊地創", 1],
    [3, "〜櫻〜", "菊地創", 1],
    [4, "〜蓮〜", "菊地創", 1],
    [5, "迷子", "菊地創", 1],
    [6, "花めく", "菊地創", 1],
    [7, "焦燥", "菊地創", 1],
    [8, "蓮呆", "菊地創", 1],
    [9, "葛藤", "菊地創", 1],
    [10, "新異", "菊地創", 1],
    [11, "不可思議", "菊地創", 1],
    [12, "街場", "菊地創", 1],
    [13, "らうたし", "菊地創", 1],
    [14, "珍妙", "菊地創", 1],
    [15, "喪失", "菊地創", 1],
    [16, "湯治", "菊地創", 1],
    [17, "水面", "菊地創", 1],
    [18, "暮夜", "菊地創", 1],
    [19, "花時姉妹", "菊地創", 1],
    [20, "春の旅路", "菊地創", 1],
    [21, "心ニ蕾", "菊地創", 1],
    [22, "「このはな綺譚」サブタイトル", "菊地創", 1],
    [23, "「このはな綺譚」アイキャッチ", "菊地創", 1],
    [24, "「このはな綺譚」次回予告", "菊地創", 1],
]
links = ["https://beta.musicbrainz.org/release/a53c06cd-3f16-4115-ba44-a4ae555f7ad4", "https://vgmdb.net/album/72191"]

[4]
catalognumber = "LACA-9566"
date = "2018-01-10"
album = "TVアニメ『このはな綺譚』おりじなるさうんどとらっく Disc 2 [LACA-9566]"
tracks = [
    [1, "〜皐〜", "菊地創", 1],
    [2, "韶光", "菊地創", 1],
    [3, "瀟洒", "菊地創", 1],
    [4, "奉公", "菊地創", 1],
    [5, "柚困", "菊地創", 1],
    [6, "〜柚〜", "菊地創", 1],
    [7, "〜棗〜", "菊地創", 1],
    [8, "逍遥", "菊地創", 1],
    [9, "沈心", "菊地創", 1],
    [10, "廃憶", "菊地創", 1],
    [11, "離離", "菊地創", 1],
    [12, "寂寥", "菊地創", 1],
    [13, "自省", "菊地創", 1],
    [14, "此花亭怪談", "菊地創", 1],
    [15, "安閑", "菊地創", 1],
    [16, "滑稽", "菊地創", 1],
    [17, "木瓜", "菊地創", 1],
    [18, "影向", "菊地創", 1],
    [19, "宿願", "菊地創", 1],
    [20, "昇華", "菊地創", 1],
    [21, "姿の花", "菊地創", 1],
    [22, "玉響", "菊地創", 1],
    [23, "夏祭", "菊地創", 1],
    [24, "夏花想々", "菊地創", 1],
    [25, "A:椴木", "菊地創", 1],
    [26, "B:聖夜", "菊地創", 1],
    [27, "四時・草の縁", "柚 (CV. 大野柚布子)", 2],
]
links = ["https://beta.musicbrainz.org/release/a53c06cd-3f16-4115-ba44-a4ae555f7ad4", "https://vgmdb.net/album/72191"]

[5]
catalognumber = "TBZR-0981"
date = "2018-02-28"
album = "ラジオCD「らじお 此花亭へようこそ」 Disc 1"
tracks = []
links = ["https://vgmdb.net/album/84141"]

[6]
catalognumber = "TBZR-0982"
date = "2018-02-28"
album = "ラジオCD「らじお 此花亭へようこそ」 Disc 2"
tracks = []
links = ["https://vgmdb.net/album/84141"]
