[1]
catalognumber = "VTCL-60016"
date = "2007-12-27"
album = "テレビ東京系アニメーション「スケッチブック～full color's～」ドラマCD スケッチブックストーリーズ～前夜祭～"
tracks = [
    [1, "文化祭への道", "[dialogue]", 0],
    [2, "究極のヤキソバ", "[dialogue]", 0],
    [3, "いっぱいの天ぷらそば", "[dialogue]", 0],
    [4, "やるきな美術部", "[dialogue]", 0],
    [5, "流れ星きらきら", "[dialogue]", 0],
    [6, "たんぽぽ水車", "桑原空(CV:花澤香菜) & 麻生夏海(CV:中世明日香) & 鳥飼葉月(CV:牧野由依)", 1],
]
links = ["https://beta.musicbrainz.org/release/97ce0f54-cf37-4582-b1d5-a88781ec945c", "https://vgmdb.net/album/67093"]

[2]
catalognumber = "VTCL-60005"
date = "2007-11-21"
album = "テレビ東京系アニメーション「スケッチブック～full color's～」オリジナルサウンドトラック"
tracks = [
    [1, "遠まわりして帰ろ", "村松健", 0],
    [2, "風さがし-TVサイズ-", "清浦夏実", 0],
    [3, "人見知りなままで ～出逢いがしら", "村松健", 0],
    [4, "人見知りなままで", "村松健", 0],
    [5, "迷子の子猫", "村松健", 0],
    [6, "小さな幸せ", "村松健", 0],
    [7, "バルーンムード ～夢から覚めても", "村松健", 0],
    [8, "微笑みのもと", "村松健", 0],
    [9, "夕焼けを歩いたね", "村松健", 0],
    [10, "春風の贈りもの", "村松健", 0],
    [11, "スピード２", "村松健", 0],
    [12, "私の時間", "村松健", 0],
    [13, "私の時間 ～また明日", "村松健", 0],
    [14, "草摘みのうた", "村松健", 0],
    [15, "お調子者のうた", "村松健", 0],
    [16, "空き地のそら ～ネコたちの自由", "村松健", 0],
    [17, "僕らの冒険", "村松健", 0],
    [18, "僕らの冒険 ～かえりみち", "村松健", 0],
    [19, "希望のへさき", "村松健", 0],
    [20, "ハッピーアワー", "村松健", 0],
    [21, "雲の澪を行く", "村松健", 0],
    [22, "夕まぐれの国", "村松健", 0],
    [23, "バルーンムード ～ピアノソロ", "村松健", 0],
    [24, "スケッチブックを持ったまま -TVサイズ-", "牧野由依", 0],
    [25, "希望のへさき ～未来編", "村松健", 0],
]
links = ["https://beta.musicbrainz.org/release/d2a24352-d736-4bac-9aa4-d6ebece33b0a", "https://vgmdb.net/album/19860"]

[3]
catalognumber = "VTCL-35003"
date = "2007-10-24"
album = "スケッチブックを持ったまま / 牧野由依"
tracks = [
    [1, "スケッチブックを持ったまま", "牧野由依", 1],
    [2, "遠くまで行こう", "牧野由依", 0],
    [3, "6つの子品 Op.118 間奏曲 イ長調", "牧野由依", 0],
    [4, "スケッチブックを持ったまま -Instrumental-", "牧野由依", 0],
    [5, "遠くまで行こう -Instrumental-", "牧野由依", 0],
]
links = ["https://beta.musicbrainz.org/release/7acf9734-1118-492a-bb5f-7a994b2e319d", "https://vgmdb.net/album/35385"]

[4]
catalognumber = "VTCL-35002"
date = "2007-10-24"
album = "風さがし / 清浦夏実"
tracks = [
    [1, "風さがし", "清浦夏実", 1],
    [2, "夏の記憶", "清浦夏実", 1],
    [3, "風さがし -Instrumental-", "清浦夏実", 0],
    [4, "夏の記憶 -Instrumental-", "清浦夏実", 0],
]
links = ["https://beta.musicbrainz.org/release/5a7bf300-3ac3-4877-835c-6e34630d4388", "https://vgmdb.net/album/24475"]
