[1]
catalognumber = ""
date = "2022-01-19"
album = "『無職転生 ～異世界行ったら本気だす～』 オリジナル・サウンドトラック2"
tracks = [
    [1, "冒険", "藤澤慶昌", "0"],
    [2, "思考", "藤澤慶昌", "0"],
    [3, "駆け引き", "藤澤慶昌", "0"],
    [4, "いたずら", "藤澤慶昌", "0"],
    [5, "まずい状況", "藤澤慶昌", "0"],
    [6, "魔力が集まる場所", "藤澤慶昌", "0"],
    [7, "ルイジェルドの怒り", "藤澤慶昌", "0"],
    [8, "掌の上", "藤澤慶昌", "0"],
    [9, "トーナとエリスの別れ", "藤澤慶昌", "0"],
    [10, "ミリス神聖国", "藤澤慶昌", "0"],
    [11, "初めての海", "藤澤慶昌", "0"],
    [12, "魔界大帝キシリカ・キシリス!?", "藤澤慶昌", "0"],
    [13, "ギレーヌのこと", "藤澤慶昌", "0"],
    [14, "信頼を得る為に", "藤澤慶昌", "0"],
    [15, "ウェンポート", "藤澤慶昌", "0"],
    [16, "密輸組織", "藤澤慶昌", "0"],
    [17, "作戦会議", "藤澤慶昌", "0"],
    [18, "笑顔の力", "藤澤慶昌", "0"],
    [19, "快適な牢屋", "藤澤慶昌", "0"],
    [20, "先輩と新入", "藤澤慶昌", "0"],
    [21, "ドルディア族", "藤澤慶昌", "0"],
    [22, "共闘", "藤澤慶昌", "0"],
    [23, "再会", "藤澤慶昌", "0"],
    [24, "冒険者", "藤澤慶昌", "0"],
    [25, "慰め", "藤澤慶昌", "0"],
    [26, "待ってる", "藤澤慶昌", "0"],
    [27, "神聖な世界", "藤澤慶昌", "0"],
    [28, "シーローン王宮", "藤澤慶昌", "0"],
    [29, "秘密の作戦", "藤澤慶昌", "0"],
    [30, "まさか!?", "藤澤慶昌", "0"],
    [31, "旅人の唄 -EP17 Inst Ver.-", "藤澤慶昌", "0"],
    [32, "ロキシーへの想い", "藤澤慶昌", "0"],
    [33, "ザノバの力", "藤澤慶昌", "0"],
    [34, "圧倒的力との遭遇", "藤澤慶昌", "0"],
]
links = ["https://beta.musicbrainz.org/release/89d88929-2452-4fbb-93fc-3a5086352176", "https://vgmdb.net/album/117523"]

[2]
catalognumber = "TBR33225D-2"
date = "2023-10-18"
album = "無職転生II ～異世界行ったら本気だす～ Original Soundtrack 1 Special Edition"
tracks = [
    [1, "復活", "藤澤慶昌", ""],
    [2, "Neck And Neck", "藤澤慶昌", ""],
    [3, "アリエルの言葉", "藤澤慶昌", ""],
    [4, "凛として", "藤澤慶昌", ""],
    [5, "永遠なれ、アスラ王国", "牧浦乙葵", ""],
    [6, "夢の中でも", "藤澤慶昌", ""],
    [7, "バシェラント公国", "藤澤慶昌", ""],
    [8, "Critical The Situation", "藤澤慶昌", ""],
    [9, "冒険者稼業", "藤澤慶昌", ""],
    [10, "敵襲", "藤澤慶昌", ""],
    [11, "自分への問いかけ", "藤澤慶昌", ""],
    [12, "脈アリ？", "藤澤慶昌", ""],
    [13, "ブルームローズの館", "藤澤慶昌", ""],
    [14, "ゾルダードの優しさ", "藤澤慶昌", ""],
    [15, "エリナリーゼ", "藤澤慶昌", ""],
    [16, "朗報", "藤澤慶昌", ""],
    [17, "ラノア魔法大学のある街", "藤澤慶昌", ""],
    [18, "ザノバ再会", "藤澤慶昌", ""],
    [19, "高飛車", "藤澤慶昌", ""],
    [20, "学校生活", "藤澤慶昌", ""],
    [21, "荒くれ者", "藤澤慶昌", ""],
    [22, "優しいフィッツ", "藤澤慶昌", ""],
    [23, "フィッツの気持ち", "藤澤慶昌", ""],
    [24, "厳しいフィッツ", "藤澤慶昌", ""],
    [25, "シルフィとして", "藤澤慶昌", ""],
    [26, "人形制作", "藤澤慶昌", ""],
    [27, "命令", "藤澤慶昌", ""],
    [28, "内緒", "藤澤慶昌", ""],
    [29, "Clover -instrumental ver.-", "藤澤慶昌", ""],
    [30, "落胆", "藤澤慶昌", ""],
    [31, "リニアとプルセナ", "藤澤慶昌", ""],
    [32, "遭遇の予感", "藤澤慶昌", ""],
    [33, "バーディガーディ", "藤澤慶昌", ""],
    [34, "ナナホシの本音", "藤澤慶昌", ""],
]
links = ["https://beta.musicbrainz.org/release/988c7918-f361-4bc3-bdf8-461633cd791f", "https://vgmdb.net/album/132782"]

[3]
catalognumber = "TBR33253D-2"
date = "2024-07-17"
album = "無職転生II ～異世界行ったら本気だす～ Original Soundtrack 2 Special Edition"
tracks = [
    [1, "幸せな日々", "藤澤慶昌", ""],
    [2, "新居探索", "藤澤慶昌", ""],
    [3, "襲いかかる人形", "藤澤慶昌", ""],
    [4, "新婚", "藤澤慶昌", ""],
    [5, "ルディとシルフィ", "藤澤慶昌", ""],
    [6, "友人からの祝福", "藤澤慶昌", ""],
    [7, "ゼニスへの思い", "藤澤慶昌", ""],
    [8, "家族のぬくもり", "藤澤慶昌", ""],
    [9, "昔の自分", "藤澤慶昌", ""],
    [10, "魔法陣", "藤澤慶昌", ""],
    [11, "ツバサ", "ナナホシ(CV:若山詩音)", ""],
    [12, "ロキシーの優しさ", "藤澤慶昌", ""],
    [13, "世渡り上手", "藤澤慶昌", ""],
    [14, "ダンジョン", "藤澤慶昌", ""],
    [15, "転移遺跡", "藤澤慶昌", ""],
    [16, "ターニングポイント", "藤澤慶昌", ""],
    [17, "旅路", "藤澤慶昌", ""],
    [18, "決死の覚悟", "藤澤慶昌", ""],
    [19, "転移迷宮", "藤澤慶昌", ""],
    [20, "迷宮都市ラパン", "藤澤慶昌", ""],
    [21, "パウロ", "藤澤慶昌", ""],
    [22, "酒場", "藤澤慶昌", ""],
    [23, "為す術無し", "藤澤慶昌", ""],
    [24, "悲愴", "藤澤慶昌", ""],
    [25, "オン・ザ・フロントライン - Piano ver.", "藤澤慶昌", ""],
]
links = ["https://beta.musicbrainz.org/release/72bb775d-564a-457a-a3dd-efd6637cb898", "https://vgmdb.net/album/132783"]

[4]
catalognumber = ""
date = "2021-04-21"
album = "『無職転生 〜異世界行ったら本気だす〜』 オリジナル・サウンドトラック1"
tracks = [
    [1, "魔術の授業", "藤澤慶昌", "0"],
    [2, "魔法が存在する世界で", "藤澤慶昌", "0"],
    [3, "詠唱", "藤澤慶昌", "0"],
    [4, "ルディの失態", "藤澤慶昌", "0"],
    [5, "小さい家庭教師“ロキシー”", "藤澤慶昌", "0"],
    [6, "無職転生", "藤澤慶昌", "0"],
    [7, "まだ見ぬ世界", "藤澤慶昌", "0"],
    [8, "ロキシーからの贈り物", "藤澤慶昌", "0"],
    [9, "外には絶望", "藤澤慶昌", "0"],
    [10, "ロキシー最後の授業", "藤澤慶昌", "0"],
    [11, "師匠のお守り", "藤澤慶昌", "0"],
    [12, "グレイラット家の日々", "藤澤慶昌", "0"],
    [13, "友達", "藤澤慶昌", "0"],
    [14, "思わぬ現実", "藤澤慶昌", "0"],
    [15, "エリスの笑顔", "藤澤慶昌", "0"],
    [16, "シルフィの涙", "藤澤慶昌", "0"],
    [17, "ロキシーからの手紙", "藤澤慶昌", "0"],
    [18, "オンリー(アコースティックVer.)", "藤澤慶昌", "0"],
    [19, "パウロ VS ルディ", "藤澤慶昌", "0"],
    [20, "ギレーヌと二人きり", "藤澤慶昌", "0"],
    [21, "エリス怒る", "藤澤慶昌", "0"],
    [22, "金でデレは買えない", "藤澤慶昌", "0"],
    [23, "サウロス登場", "藤澤慶昌", "0"],
    [24, "お願いにゃん", "藤澤慶昌", "0"],
    [25, "ギレーヌの誘導", "藤澤慶昌", "0"],
    [26, "剣術指導", "藤澤慶昌", "0"],
    [27, "魔法を使わないダンス", "藤澤慶昌", "0"],
    [28, "5年後の約束!", "藤澤慶昌", "0"],
    [29, "ヒトガミの助言", "藤澤慶昌", "0"],
    [30, "大切な仲間", "藤澤慶昌", "0"],
]
links = ["https://beta.musicbrainz.org/release/fe921e86-4692-425f-8bbe-e5fa76429d9b", "https://vgmdb.net/album/117110"]

[5]
catalognumber = "[none]"
date = "2023-09-25"
album = "『無職転生 ～異世界行ったら本気だす～』 第2期 オリジナル・サウンドトラック"
tracks = [
    [1, "無詠唱魔術", "藤澤慶昌", ""],
    [2, "アリエルの言葉", "藤澤慶昌", ""],
    [3, "凛として", "藤澤慶昌", ""],
    [4, "永遠なれ、アスラ王国", "牧浦乙葵", ""],
    [5, "姑息な鼠", "藤澤慶昌", ""],
    [6, "夢の中でも", "藤澤慶昌", ""],
    [7, "Critical The Situation", "藤澤慶昌", ""],
    [8, "冒険者稼業", "藤澤慶昌", ""],
    [9, "敵襲", "藤澤慶昌", ""],
    [10, "取り分", "藤澤慶昌", ""],
    [11, "カウンターアローとの時間", "藤澤慶昌", ""],
    [12, "依頼の準備", "藤澤慶昌", ""],
    [13, "自分への問いかけ", "藤澤慶昌", ""],
    [14, "脈アリ?", "藤澤慶昌", ""],
    [15, "ブルームローズの館", "藤澤慶昌", ""],
    [16, "ゾルダードの優しさ", "藤澤慶昌", ""],
    [17, "エリナリーゼ", "藤澤慶昌", ""],
    [18, "吟遊詩人", "藤澤慶昌", ""],
    [19, "朗報", "藤澤慶昌", ""],
    [20, "知りたい情報", "藤澤慶昌", ""],
    [21, "トラブル回避", "藤澤慶昌", ""],
    [22, "ラノア魔法大学のある街", "藤澤慶昌", ""],
    [23, "ラノア魔法大学について", "藤澤慶昌", ""],
    [24, "ザノバ再会", "藤澤慶昌", ""],
    [25, "優しいフィッツ", "藤澤慶昌", ""],
    [26, "フィッツの気持ち", "藤澤慶昌", ""],
    [27, "厳しいフィッツ", "藤澤慶昌", ""],
    [28, "シルフィとして", "藤澤慶昌", ""],
    [29, "アスラ王国第二王女", "藤澤慶昌", ""],
    [30, "内緒", "藤澤慶昌", ""],
    [31, "Clover -instrumental ver.-", "藤澤慶昌", ""],
    [32, "歓喜", "藤澤慶昌", ""],
    [33, "転移事件の真相", "藤澤慶昌", ""],
    [34, "リニアとプルセナ", "藤澤慶昌", ""],
    [35, "バーディガーディ", "藤澤慶昌", ""],
    [36, "陽気な男", "藤澤慶昌", ""],
    [37, "人形生活のはじまり", "藤澤慶昌", ""],
    [38, "白い仮面", "藤澤慶昌", ""],
]
links = ["https://beta.musicbrainz.org/release/08c66b46-0672-4efb-82c8-6fdc0f74a968", "https://vgmdb.net/album/132779"]

[6]
catalognumber = "TBR31096D-2"
date = "2022-01-19"
album = "無職転生 ～異世界行ったら本気だす～ Original Soundtrack 2 Special Edition"
tracks = [
    [1, "心の奥底", "藤澤慶昌", "0"],
    [2, "もう大丈夫", "藤澤慶昌", "0"],
    [3, "格式ある家系", "藤澤慶昌", "0"],
    [4, "計略", "藤澤慶昌", "0"],
    [5, "目的", "藤澤慶昌", "0"],
    [6, "したごころ", "藤澤慶昌", "0"],
    [7, "陽気な日", "藤澤慶昌", "0"],
    [8, "額の目", "藤澤慶昌", "0"],
    [9, "知っていること", "藤澤慶昌", "0"],
    [10, "たくらみ", "藤澤慶昌", "0"],
    [11, "アジト", "藤澤慶昌", "0"],
    [12, "虚無の世界", "藤澤慶昌", "0"],
    [13, "アイシャ", "藤澤慶昌", "0"],
    [14, "初めての海", "藤澤慶昌", "0"],
    [15, "魔界大帝キシリカ・キシリス!?", "藤澤慶昌", "0"],
    [16, "ギレーヌのこと", "藤澤慶昌", "0"],
    [17, "信頼を得る為に", "藤澤慶昌", "0"],
    [18, "ウェンポート", "藤澤慶昌", "0"],
    [19, "密輸組織", "藤澤慶昌", "0"],
    [20, "作戦会議", "藤澤慶昌", "0"],
    [21, "笑顔の力", "藤澤慶昌", "0"],
    [22, "快適な牢屋", "藤澤慶昌", "0"],
    [23, "先輩と新入", "藤澤慶昌", "0"],
    [24, "ドルディア族", "藤澤慶昌", "0"],
    [25, "共闘", "藤澤慶昌", "0"],
    [26, "再会", "藤澤慶昌", "0"],
    [27, "冒険者", "藤澤慶昌", "0"],
    [28, "慰め", "藤澤慶昌", "0"],
    [29, "待ってる", "藤澤慶昌", "0"],
    [30, "神聖な世界", "藤澤慶昌", "0"],
    [31, "シーローン王宮", "藤澤慶昌", "0"],
    [32, "秘密の作戦", "藤澤慶昌", "0"],
    [33, "まさか!?", "藤澤慶昌", "0"],
    [34, "旅人の唄 -EP17 Inst Ver.-", "藤澤慶昌", "0"],
    [35, "ロキシーへの想い", "藤澤慶昌", "0"],
    [36, "ザノバの力", "藤澤慶昌", "0"],
    [37, "圧倒的力との遭遇", "藤澤慶昌", "0"],
]
links = ["https://beta.musicbrainz.org/release/f77d5fdc-75e6-436c-8bb1-3642876d406c", "https://vgmdb.net/album/108264"]

[7]
catalognumber = "TBR31094D-2"
date = "2021-04-21"
album = "無職転生 ～異世界行ったら本気だす～ Original Soundtrack 1 Special Edition"
tracks = [
    [1, "魔術の授業", "藤澤慶昌", "0"],
    [2, "魔法が存在する世界で", "藤澤慶昌", "0"],
    [3, "詠唱", "藤澤慶昌", "0"],
    [4, "ルディの失態", "藤澤慶昌", "0"],
    [5, "小さい家庭教師\"ロキシー\"", "藤澤慶昌", "0"],
    [6, "ロキシーの訓練", "藤澤慶昌", "0"],
    [7, "無職転生", "藤澤慶昌", "0"],
    [8, "5歳のお祝い", "藤澤慶昌", "0"],
    [9, "ルディのナイスガイスキル", "藤澤慶昌", "0"],
    [10, "まだ見ぬ世界", "藤澤慶昌", "0"],
    [11, "ロキシーからの贈り物", "藤澤慶昌", "0"],
    [12, "外には絶望", "藤澤慶昌", "0"],
    [13, "ロキシー最後の授業", "藤澤慶昌", "0"],
    [14, "師匠のお守り", "藤澤慶昌", "0"],
    [15, "グレイラット家の日々", "藤澤慶昌", "0"],
    [16, "友達", "藤澤慶昌", "0"],
    [17, "思わぬ現実", "藤澤慶昌", "0"],
    [18, "シルフに教える魔術", "藤澤慶昌", "0"],
    [19, "シルフィの涙", "藤澤慶昌", "0"],
    [20, "ロキシーからの手紙", "藤澤慶昌", "0"],
    [21, "オンリー(アコースティックVer.)", "藤澤慶昌", "0"],
    [22, "ギレーヌ登場", "藤澤慶昌", "0"],
    [23, "パウロ VS ルディ", "藤澤慶昌", "0"],
    [24, "ボレアス家", "藤澤慶昌", "0"],
    [25, "エリス怒る", "藤澤慶昌", "0"],
    [26, "金でデレは買えない", "藤澤慶昌", "0"],
    [27, "サウロス登場", "藤澤慶昌", "0"],
    [28, "ギレーヌの誘導", "藤澤慶昌", "0"],
    [29, "剣術指導", "藤澤慶昌", "0"],
    [30, "ボレアス邸の一日", "藤澤慶昌", "0"],
    [31, "10歳の宴", "藤澤慶昌", "0"],
    [32, "魔法を使わないダンス", "藤澤慶昌", "0"],
    [33, "5年後の約束!", "藤澤慶昌", "0"],
    [34, "ヒトガミの助言", "藤澤慶昌", "0"],
    [35, "ルイジェルド", "藤澤慶昌", "0"],
    [36, "ノコパラの陰謀", "藤澤慶昌", "0"],
    [37, "旅人の唄(アコースティックVer.)", "藤澤慶昌", "0"],
]
links = ["https://beta.musicbrainz.org/release/e7f11867-4cc6-4fab-b6dc-594d45919f94", "https://vgmdb.net/album/108263"]

[8]
catalognumber = "THCA-60269"
date = "2021-12-22"
album = "TVアニメ『無職転生～異世界行ったら本気出す～』Theme Song Collection"
tracks = [
    [1, "旅人の唄", "大原ゆい子", "0"],
    [2, "目覚めの唄", "大原ゆい子", "0"],
    [3, "継承の唄", "大原ゆい子", "0"],
    [4, "祈りの唄", "大原ゆい子", "0"],
    [5, "遠くの子守の唄", "大原ゆい子", "0"],
    [6, "旅人の唄～帰郷～", "大原ゆい子", "0"],
    [7, "オンリー", "大原ゆい子", "0"],
    [8, "風と行く道", "大原ゆい子", "1"],
]
links = ["https://beta.musicbrainz.org/release/47abf02c-74d4-40ef-a0cf-a9c6372c6418", "https://vgmdb.net/album/114953"]

[9]
catalognumber = "[none]"
date = "2024-07-02"
album = "『無職転生 ～異世界行ったら本気だす～』 第2期 オリジナル・サウンドトラック2"
tracks = [
    [1, "幸せな日々", "藤澤慶昌", ""],
    [2, "新居探索", "藤澤慶昌", ""],
    [3, "襲いかかる人形", "藤澤慶昌", ""],
    [4, "新婚", "藤澤慶昌", ""],
    [5, "ルディとシルフィ", "藤澤慶昌", ""],
    [6, "友人からの祝福", "藤澤慶昌", ""],
    [7, "ゼニスへの思い", "藤澤慶昌", ""],
    [8, "家族のぬくもり", "藤澤慶昌", ""],
    [9, "昔の自分", "藤澤慶昌", ""],
    [10, "魔法陣", "藤澤慶昌", ""],
    [11, "ツバサ", "ナナホシ(CV:若山詩音)", ""],
    [12, "ロキシーの優しさ", "藤澤慶昌", ""],
    [13, "世渡り上手", "藤澤慶昌", ""],
    [14, "ダンジョン", "藤澤慶昌", ""],
    [15, "転移遺跡", "藤澤慶昌", ""],
    [16, "ターニングポイント", "藤澤慶昌", ""],
    [17, "旅路", "藤澤慶昌", ""],
    [18, "決死の覚悟", "藤澤慶昌", ""],
    [19, "転移迷宮", "藤澤慶昌", ""],
    [20, "迷宮都市ラパン", "藤澤慶昌", ""],
    [21, "パウロ", "藤澤慶昌", ""],
    [22, "酒場", "藤澤慶昌", ""],
    [23, "為す術無し", "藤澤慶昌", ""],
    [24, "悲愴", "藤澤慶昌", ""],
]
links = ["https://beta.musicbrainz.org/release/aede0218-9471-4845-9e4f-3a21683be509", "https://vgmdb.net/album/141120"]

[10]
catalognumber = "THCA-60295"
date = "2024-09-18"
album = "TVアニメ『無職転生Ⅱ ～異世界行ったら本気だす～』エンディングテーマコレクション"
tracks = [
    [1, "Clover", "大原ゆい子", ""],
    [2, "ムスビメ", "大原ゆい子", ""],
    [3, "花咲み", "シルフィエット(CV:茅野愛衣)", ""],
    [4, "守りたいもの", "大原ゆい子", ""],
    [5, "ツバサ", "ナナホシ(CV:若山詩音)", ""],
    [6, "かげくらべの唄", "大原ゆい子", ""],
]
links = ["https://beta.musicbrainz.org/release/3a49b707-8710-4e0d-9d3b-8f469797d9f7", "https://vgmdb.net/album/142154"]
